### ISSUE TITLE
How to calculate the additional reward in the Figure 1

### ISSUE THREAD

**Issue by xtjjyygy** [lascavana/rl2branch#3]
![image](https://github.com/lascavana/rl2branch/assets/38133593/ae3b0c49-f5d1-45b9-9ebc-2a067642a617)

It's an honor to have read your paper, but I am confused with the additional reward in Figure 1

Thanks

**Comment by lascavana** [comment]
The difference is the following. In a tree MDP an action is credited for everything that happens in the subtree rooted at the node where the action was taken. In an MDP, an action is credited for everything that happens after the action was taken. This necessarily *includes* the subtree, plus perhaps some other parts of the tree. 
In the example above, we see how the action at node f can receive more reward signals depending on the processing order. For example, in the top MDP rollout, after the subtree nodes are processed (h, i) the process continues on node e. This means that the reward obtained in e is credited to f (i.e. an additional term is added to the summation). Instead of r_h + r_i the node receives r_h + r_i + r_e
![266349511-ae3b0c49-f5d1-45b9-9ebc-2a067642a617](https://github.com/lascavana/rl2branch/assets/26193199/4dfa877b-cca3-4df6-97e2-768544cc0a08)


I hope this clarifies your question!
